### ISSUE TITLE
provide help

### ISSUE THREAD

**Issue by hypnopump** [masashitsubaki/QuantumDeepField_crystal#1]
Hi there!

I came accross your project QDF a month ago and i found it awesome! Cool application of inductive bias to mitigate Deep Learning overfitting!
So i've been taking a look at this repo bc it's super interesting as well but i haven't seen any activity in the last month so i was wondering if the project is in stand-by or there's work been done or there's any kind of problem (if so, I could try to help and push this forward!)

Cheers and keep it up!

**Comment by masashitsubaki** [comment]
Thank you very much for your interest in our work!

I'm sorry that we are now implementing the code and writing the paper. Actually, in order to extend the current QDF model from organic molecules to inorganic crystals, we have some challenges to be addressed and new QDF will be very different from the QDF specific to organic molecules. Actually, we already have the repository of this project but we still can't share it because it is a closed repository in our research institute.

We will share the repository after publishing our paper as a journal. Please wait for a while.

Again,  thank you for your interest.

**Comment by hypnopump** [comment]
Oh cool! I'll be happy to see the results once they come out!
